export interface CharacterInfo {
  id: string;
  name: string;
  nameEn: string;
  rarity: 4 | 5;
  element: string;
  path: string;
  faction: string;
  releaseVersion: string;
}

// HSR 角色列表（前20个高人气角色）
export const CHARACTER_LIST: CharacterInfo[] = [
  // 5星角色
  {
    id: 'kafka',
    name: '卡芙卡',
    nameEn: 'Kafka',
    rarity: 5,
    element: 'Lightning',
    path: 'Nihility',
    faction: 'Stellaron Hunter',
    releaseVersion: '1.2',
  },
  {
    id: 'acheron',
    name: '黄泉',
    nameEn: 'Acheron',
    rarity: 5,
    element: 'Lightning',
    path: 'Nihility',
    faction: 'Galaxy Ranger',
    releaseVersion: '2.1',
  },
  {
    id: 'firefly',
    name: '流萤',
    nameEn: 'Firefly',
    rarity: 5,
    element: 'Fire',
    path: 'Destruction',
    faction: 'Stellaron Hunter',
    releaseVersion: '2.3',
  },
  {
    id: 'acheron',
    name: '黄泉',
    nameEn: 'Acheron',
    rarity: 5,
    element: 'Lightning',
    path: 'Nihility',
    faction: 'Galaxy Ranger',
    releaseVersion: '2.1',
  },
  {
    id: 'dan-heng-imbibitor-lunae',
    name: '丹恒·饮月',
    nameEn: 'Dan Heng • Imbibitor Lunae',
    rarity: 5,
    element: 'Imaginary',
    path: 'Destruction',
    faction: 'Train Crew',
    releaseVersion: '1.3',
  },
  {
    id: 'blade',
    name: '刃',
    nameEn: 'Blade',
    rarity: 5,
    element: 'Wind',
    path: 'Destruction',
    faction: 'Stellaron Hunter',
    releaseVersion: '1.2',
  },
  {
    id: 'jing-yuan',
    name: '景元',
    nameEn: 'Jing Yuan',
    rarity: 5,
    element: 'Lightning',
    path: 'Erudition',
    faction: 'Luocha',
    releaseVersion: '1.0',
  },
  {
    id: 'seele',
    name: '希儿',
    nameEn: 'Seele',
    rarity: 5,
    element: 'Quantum',
    path: 'Hunt',
    faction: 'Wildfire',
    releaseVersion: '1.0',
  },
  {
    id: 'silver-wolf',
    name: '银狼',
    nameEn: 'Silver Wolf',
    rarity: 5,
    element: 'Quantum',
    path: 'Nihility',
    faction: 'Stellaron Hunter',
    releaseVersion: '1.1',
  },
  {
    id: 'fu-xuan',
    name: '符玄',
    nameEn: 'Fu Xuan',
    rarity: 5,
    element: 'Quantum',
    path: 'Preservation',
    faction: 'Divination Commission',
    releaseVersion: '1.3',
  },
  {
    id: 'ruan-mei',
    name: '阮·梅',
    nameEn: 'Ruan Mei',
    rarity: 5,
    element: 'Ice',
    path: 'Harmony',
    faction: 'Divination Commission',
    releaseVersion: '1.6',
  },
  {
    id: 'robin',
    name: '知更鸟',
    nameEn: 'Robin',
    rarity: 5,
    element: 'Physical',
    path: 'Harmony',
    faction: 'Penacony',
    releaseVersion: '2.2',
  },
  {
    id: 'sparkle',
    name: '花火',
    nameEn: 'Sparkle',
    rarity: 5,
    element: 'Quantum',
    path: 'Harmony',
    faction: 'Masked Fools',
    releaseVersion: '2.0',
  },
  {
    id: 'black-swans',
    name: '黑天鹅',
    nameEn: 'Black Swan',
    rarity: 5,
    element: 'Wind',
    path: 'Nihility',
    faction: 'Garden of Recollection',
    releaseVersion: '2.0',
  },
  {
    id: 'aventurine',
    name: '砂金',
    nameEn: 'Aventurine',
    rarity: 5,
    element: 'Imaginary',
    path: 'Preservation',
    faction: 'Interastral Peace Corporation',
    releaseVersion: '2.1',
  },
  {
    id: 'boothill',
    name: '波提欧',
    nameEn: 'Boothill',
    rarity: 5,
    element: 'Physical',
    path: 'Hunt',
    faction: 'Galaxy Ranger',
    releaseVersion: '2.2',
  },
  // 4星角色
  {
    id: 'gallagher',
    name: '加拉赫',
    nameEn: 'Gallagher',
    rarity: 4,
    element: 'Fire',
    path: 'Abundance',
    faction: 'Penacony',
    releaseVersion: '2.1',
  },
  {
    id: 'harmony-mc',
    name: '同谐主角',
    nameEn: 'Harmony Trailblazer',
    rarity: 4,
    element: 'Imaginary',
    path: 'Harmony',
    faction: 'Astral Express',
    releaseVersion: '2.2',
  },
  {
    id: 'march-7th',
    name: '三月七',
    nameEn: 'March 7th',
    rarity: 4,
    element: 'Ice',
    path: 'Preservation',
    faction: 'Astral Express',
    releaseVersion: '1.0',
  },
  {
    id: 'trailblazer',
    name: '开拓者',
    nameEn: 'Trailblazer',
    rarity: 4,
    element: 'Physical',
    path: 'Destruction',
    faction: 'Astral Express',
    releaseVersion: '1.0',
  },
];

// 去重
export const UNIQUE_CHARACTERS = CHARACTER_LIST.filter(
  (char, index, self) => index === self.findIndex(c => c.id === char.id)
);
